name: Uint-Test

on:
  push:
    branches:
      - master
      - "release-[0-9].[0-9]*"
    paths-ignore:
      - '**/*.md'
      - '**/OWNERS'
      - 'OWNERS'
      - 'OWNERS_ALIASES'

  pull_request:
    branches:
      - master
      - "release-[0-9].[0-9]*"
    paths-ignore:
      - '**/*.md'
      - '**/OWNERS'
      - 'OWNERS'
      - 'OWNERS_ALIASES'

# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency.
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  dispatcher_unit_test:
    runs-on: ubuntu-latest 
    name: Dispatcher Unit Test
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Unit Test
        run: |
          cd pkg/sink/mysql
          go test --tags=intest
          cd ../util
          go test
          cd ../../../downstreamadapter/sink/
          go test ./... --tags=intest
          cd ../dispatcher
          go test --tags=intest
          cd ../worker
          go test ./... --tags=intest
          cd ../../pkg/sink/codec
          cd open
          go test  --tags=intest
          cd ../canal
          go test  --tags=intest

  maintainer_unit_test:
    runs-on: ubuntu-latest 
    name: Maintainer Unit Test
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Unit Test
        run: |
          go test --tags=intest -timeout 120s  github.com/pingcap/ticdc/maintainer/...

  coordinator_unit_test:
    runs-on: ubuntu-latest 
    name: Coordinator And EventService Unit Test
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Unit Test
        run: |
          go test --tags=intest -timeout 120s  github.com/pingcap/ticdc/coordinator/...

